export default {
    SORTER: "SORTER",
    SET_PAGE: "SET_PAGE",
    SET_CITY: "SET_CITY",
    SET_ITEMS: "SET_ITEMS",
    SET_ORDER: "SET_ORDER",
    SET_CATEGORY: "SET_CATEGORY",
    SET_HOME_ITEMS: "SET_HOME_ITEMS",
    SET_DESCRIPTION: "SET_DESCRIPTION",
    ADD_ITEM: "ADD_ITEM",
    DEL_ITEM: "DEL_ITEM",
    SET_COUNT: "SET_COUNT",
    IS_MODAL: "IS_MODAL"
};